#for ec2 deployment
# services:
#   redis:
#     image: redis:7
#     container_name: redis
#     ports:
#       - "6379:6379"

#   qdrant:
#     image: qdrant/qdrant:latest
#     container_name: qdrant
#     ports:
#       - "6333:6333"
#       - "6334:6334"
#     volumes:
#       - qdrant_storage:/qdrant/storage

#   fastapi:
#     image: softvence/fastapi:latest
#     container_name: fastapi_app
#     ports:
#       - "8080:8080"
#     depends_on:
#       redis:
#         condition: service_started
#       qdrant:
#         condition: service_started
#     env_file:
#       - .env

#   celery_worker:
#     image: softvence/celery_worker:latest
#     container_name: celery_worker
#     command: celery -A app.celery_app worker --loglevel=info --pool=solo
#     depends_on:
#       redis:
#         condition: service_started
#       qdrant:
#         condition: service_started
#     env_file:
#       - .env

#   celery_beat:
#     image: softvence/celery_beat:latest
#     container_name: celery_beat
#     command: celery -A app.celery_app beat --loglevel=info
#     depends_on:
#       redis:
#         condition: service_started
#       qdrant:
#         condition: service_started
#     env_file:
#       - .env

# volumes:
#   qdrant_storage:

#for local development use this docker-compose file
# services:
#   redis:
#     image: redis:7
#     container_name: redis
#     ports:
#       - "6379:6379"

#   qdrant:
#     image: qdrant/qdrant:latest
#     container_name: qdrant
#     ports:
#       - "6333:6333"
#       - "6334:6334"
#     volumes:
#       - qdrant_storage:/qdrant/storage

#   fastapi:
#     build: .
#     container_name: fastapi_app
#     ports:
#       - "8080:8080"
#     depends_on:
#       redis:
#         condition: service_started
#       qdrant:
#         condition: service_started
#     env_file:
#       - .env

#   celery_worker:
#     build: .
#     container_name: celery_worker
#     command: celery -A app.celery_app worker --loglevel=info --pool=solo
#     depends_on:
#       redis:
#         condition: service_started
#       qdrant:
#         condition: service_started
#     env_file:
#       - .env

#   celery_beat:
#     build: .
#     container_name: celery_beat
#     command: celery -A app.celery_app beat --loglevel=info
#     depends_on:
#       redis:
#         condition: service_started
#       qdrant:
#         condition: service_started
#     env_file:
#       - .env

# volumes:
#   qdrant_storage:
