openai:
  model: "gpt-4o-mini"
  temperature: 0.7
  embedding_model: "text-embedding-3-large"


logger:
  log_dir: "logs"


api:
  api_1: "https://services.boats.com/pls/boats/search?key=9424cb9fae&fields=NumberOfEngines,DryWeightMeasure,WaterTankCapacityMeasure,FuelTankCapacityMeasure,HoldingTankCapacityMeasure,TotalEnginePowerQuantity,GeneralBoatDescription,AdditionalDetailDescription,DocumentID,MakeString,Model,ModelYear,BoatLocation,BoatCityNameNoCaseAlnumOnly,Price,OriginalPrice,CompanyName,Office,NominalLength,LengthOverall,BeamMeasure,MaxDraft,Engines,TotalEnginePowerQuantity,Images"
  api_2: "https://api.boats.com/inventory/search?key=YawGVsdoOdbfivrATkE4DM1XIGOEn1"


database_loc:
  raw_data_loc: "database/raw_json_data/"
  process_data_loc: "database/process_csv_data/"

# Data Preprocessing
columns:
  keep: [
    "GeneralBoatDescription",
    "AdditionalDetailDescription",
    "DocumentID",

    "MakeString",
    "Model",
    "ModelYear",

    "BoatLocation",
    "BoatCityNameNoCaseAlnumOnly",

    "Price",

    "NominalLength",
    "LengthOverall",
    "BeamMeasure",

    "Engines",
    "TotalEnginePowerQuantity",
    "NumberOfEngines",
    "Images"
  ]

# Vector Database
vector:
  url: "http://localhost:6333"
  collection_name: "boat_vector_data"
  dim_size: 3072


# Search engine
search:
  pre_index_data_loc: "indexDatabase/"
  elastic_url: "https://localhost:9200"
  user: "elastic"
  pass: "xARs94-gKY_Sc3gZSCzv"
  # certificate: "certs/ca.crt"
  