openai:
  model: "gpt-4o-mini"
  temperature: 0.7
  embedding_model: "text-embedding-3-large"


logger:
  log_dir: "logs"


# api:
#   api_1: "https://services.boats.com/pls/boats/search?key=9424cb9fae&fields=NumberOfEngines,DryWeightMeasure,WaterTankCapacityMeasure,FuelTankCapacityMeasure,HoldingTankCapacityMeasure,TotalEnginePowerQuantity,GeneralBoatDescription,AdditionalDetailDescription,DocumentID,MakeString,Model,ModelYear,BoatLocation,BoatCityNameNoCaseAlnumOnly,Price,OriginalPrice,CompanyName,Office,NominalLength,LengthOverall,BeamMeasure,MaxDraft,Engines,TotalEnginePowerQuantity,Images"
#   api_2: "https://api.boats.com/inventory/search?key=YawGVsdoOdbfivrATkE4DM1XIGOEn1"
api:
  # api_1: "https://api.floridayachttrader.com/api/boats/merged/all-sources"
  api_1: "https://api.floridayachttrader.com/api/boats/all"
  api_2: "https://api.floridayachttrader.com/api/boats/merged/all-sources" 
  api_3: "https://api.jupitermarinesales.com/api/boats-com/ai"
  api_4: "https://api.jupitermarinesales.com/api/yachtbroker/ai"

database_loc:
  raw_data_loc_florida: "database/raw_json_data_florida/"
  raw_data_loc_jupiter: "database/raw_json_data_jupiter/"
  process_data_loc_florida: "database/process_csv_data_florida/"
  process_data_loc_jupiter: "database/process_csv_data_jupiter/"

# Data Preprocessing
columns:
  keep: [
    "Source",
    "GeneralBoatDescription",
    "AdditionalDetailDescription",
    "DocumentID",

    "MakeString",
    "Model",
    "ModelYear",

    "BoatLocation",
    "BoatCityNameNoCaseAlnumOnly",

    "Price",

    "NominalLength",
    "LengthOverall",
    "BeamMeasure",

    "Engines",
    "TotalEnginePowerQuantity",
    "NumberOfEngines",
    "Images"
  ]

# Vector Database
vector:
  #url: "http://localhost:6333"
  #starting docker: docker run -p 6333:6333 -p 6334:6334 qdrant/qdrant

  #__For production__#
  url: "http://qdrant:6333"
  collection_name_florida: "florida_yacht_sales"
  collection_name_jupiter: "jupiter_marine_sales"
  dim_size: 3072

